### ISSUE TITLE
Elements stay in a static position through their animations when scrolling

### ISSUE THREAD

**Issue by brocococonut** [justintaddei/illusory#8]
As the title explains, when you scroll (vertically or horizontally) the elements stay in the same place/path on screen as they would if you hadn't scrolled

This leads to the element locations ending up not where they're meant to

It might be a bit expensive, but it'd likely be a good idea to add the current scroll value to the x/y coordinates of the elements on each frame so as to avoid the elements looking out of place.

**Comment by justintaddei** [comment]
Thanks for creating an issue!

I was originally thinking that by calculating the scroll position on each frame it would force a layout update (but I haven't actually tired to confirmed this yet).

One possible way around that might be by storing the scroll position at the start and only updating it when a `scroll` event fires. Maybe...

Nonetheless, I think it is an important feature. What would you think about a `relativeToDocument` or `lockToScroll` option (name suggestions welcome)?

**Comment by brocococonut** [comment]
Hmm.. I think `relativeToDocument` would be a better option name. I can't think of any myself, but that option would suggest it would stay where it is in relation to the document even while scrolling.

**Comment by justintaddei** [comment]
The other thing to think about is scrollable containers within the document. I'm on the road right now but I can experiment more in the morning. Not sure how to detect if there are containers to worry about in an efficient manner since scroll events don't bubble. If you have any ideas on that let me know. 

I'll get back to you tomorrow once I have a minute to play around with it.

**Comment by brocococonut** [comment]
Hmm.. Well, you could always just read the parent container's `scrollTop` property to get the current vertical scroll (and `scrollLeft` for the horizontal) then use absolute positioning and offset things that way.

**Comment by justintaddei** [comment]
I'm currently using fixed positioned elements for the animation to get around a whole bunch of other issues. If I can find a way to do delegation for scroll events this will be pretty easy to pull off. Otherwise, I think the next best option would be to walk the DOM tree and locate every scrollable container.

**Comment by justintaddei** [comment]
So I was never really worried about the performance of the `scroll` handlers themselves. I knew I could optimize those to be fast enough. What did concern me, however, was the overhead of having to walk the DOM tree (`scroll` events don't bubble) starting at the "from element" so see if any parent elements were scrollable (by checking if `scrollHeight > offsetHeight`).

**The solution**

After thinking it over for a while I remembered that events go through a "capturing" phase before bubbling, during which, they start at the root element and work their way down the tree until the target. This seems to work perfectly because it allows me to delegate every scroll event on the page to a single handler on `window`. The impact on performance may be so small that I it can be the default (and only) behavior for the library. This will be added in the v2 release along with another breaking change to the API (see #13 for details on that)

You can see it working here: https://codesandbox.io/s/capturing-all-scroll-events-xc8wi?file=/src/index.js

I should have a working example within illusory in a few days.

**Comment by justintaddei** [comment]
Okay, so after experimenting a little more I couldn't find a way to calculate the scroll delta without first knowing the elements that might scroll later.

To get around that, instead of using `relativeToDocument`, I think it should be an array of elements to be listened to for scroll events.


```ts
const scrollableContainer = document.querySelector('.scollable')

illusory(from, to, {
    // Will listen to scroll events from `window` and `scrollableContainer`
    relativeTo: [window, scrollableContainer]
})
```

This also means that the position doesn't need to be relative to the parent element, it could be a sibling or any other element that emits a `scroll` event.

**Comment by justintaddei** [comment]
v2.0.0 has just been released. It provides the discussed `relativeTo` option.
